training_data_paths:
- "./dataset/solar.arrow"
probability:
- 1.0
eval_data_paths:
- "./dataset/eval/solar.arrow"
context_length: 512
prediction_length: 96
min_past: 60
max_steps: 2_000
save_steps: 1_000
log_steps: 100
per_device_train_batch_size: 64
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 5
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: ./checkpoints/chronos-t5-small
model_type: seq2seq
random_init: false
tie_embeddings: true
output_dir: ./output/solar/
tf32: false
torch_compile: false
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
